(function(){function A(a,b){var c=b||"";if(a)try{c=decodeURIComponent(a)}catch(d){}return c}function h(a){var b=[],c,d;for(c in a)a.hasOwnProperty(c)&&(d=""+a[c],b.push(0==c.indexOf(s)?d:c+"="+encodeURIComponent(d)));return b.join("&")}function B(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}function C(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function j(a,b){return a&&a.getAttribute?a.getAttribute(b)||"":""}function P(){var a=f.getElementById("tb-beacon-aplus");
return j(a,"exparams")}function D(){p=p||f.getElementsByTagName("head")[0];return E||(p?E=p.getElementsByTagName("meta"):[])}function F(a,b){var c=a.split(";"),d,e=c.length,g,f;for(d=0;d<e;d++)g=c[d].split("="),(f="string"==typeof g[0]?g[0].replace(/^\s+|\s+$/g,""):"")&&(b[f]=A("string"==typeof g[1]?g[1].replace(/^\s+|\s+$/g,""):""))}function G(a){return(a=f.cookie.match(RegExp("\\b"+a+"=([^;]+)")))?a[1]:""}function Q(){var a,b,c=D(),d=c.length;for(a=0;a<d;a++)b=c[a],"microscope-data"==j(b,"name")&&
(b=j(b,"content"),F(b,k));h(k);u=k.siteInstanceId||k.shopId}function R(){var a,b,c=D(),d=c.length;for(a=0;a<d;a++)b=c[a],"atp-beacon"==j(b,"name")&&(b=j(b,"content"),F(b,q));h(q)}function S(){if("undefined"!=typeof l)return l;var a=f.getElementsByTagName("head")[0],b,c,d=a?a.getElementsByTagName("meta"):null;if(d){b=0;for(c=d.length;b<c;b++)if(a=d[b],"spm-id"==a.getAttribute("name"))return m=j(a,"content"),0<=m.indexOf(":")&&(a=m.split(":"),H="i"==a[0]?"i":"u",m=a[1]),l=0==m.indexOf("110")?null:m}return l=
e.SPMID||e.spmId||null}function T(){var a=new Date,b=Math.floor(1E7*Math.random());r=""+a.getMonth()+a.getDay()+a.getHours()+a.getMinutes()+a.getSeconds()+"."+b}function v(a){var a=(a||"").split("#")[0].split("?")[0],b=a.length;if(b){for(var a=b+"#"+a.charCodeAt(b-1),c=a.length,d=0,b=0;b<c;b++)d=31*d+a.charCodeAt(b);a=d}else a=-1;return a}function I(){if(!w){var a=e.name||"",b=x?f.referrer||i:i,c={refer_pv_id:r};o&&(c.wm_referrer=b);if(-1==a.indexOf("="))c.wm_old_value=a,e.name=h(c);else{x&&a.match(/&?\bwm_referrer=[^&]+/)&&
delete c.wm_referrer;for(var a=a.split("&"),b=0,d=a.length,t,g={};b<d;b++)t=a[b].split("="),g[t[0]]=A(t[1]);a=g;C(a,c);e.name=h(a)}}}function J(a,b,c){a[U]((K?"on":"")+b,function(a){a=a||e.event;c(a,a.target||a.srcElement)},y)}function V(){var a,b,c="/theme/info/info /promo/co_header.php fast_buy.htm /add_collection.htm /taobao_digital_iframe /promo/co_header_taoinfo.php /list_forum /theme/info/info".split(" ");a=0;for(b=c.length;a<b;a++)if(-1!=W.indexOf(c[a]))return L;return y}function M(){var a=
e.goldlog_queue,b,c,d;if(a&&"[object Array]"===Object.prototype.toString.call(a)&&a.length)for(;b=a.shift();)if(b&&b.action&&"string"==typeof b.action&&b.arguments&&"[object Array]"===Object.prototype.toString.call(b.arguments)){d=b.action.split(".");for(c=e;d.length;)if(c=c[d.shift()],!c)return;if("function"==typeof c)try{c.apply(c,b.arguments)}catch(f){}}}function X(){var a=function(){M();setTimeout(a,200)};a();J(e,"beforeunload",M)}function N(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}
function O(a,b){var c=y,d;if(!b)return null;for(d in b)if(b.hasOwnProperty(d)){c=L;break}return c?n.send(a,b):null}var e=window,f=document,o="https:"==f.location.protocol;if(!o&&!e._pw_aplus_loaded){e._pw_aplus_loaded=1;var w=parent!==self,Y=(o?"https://img":"http://www")+".atpanel.com/",Z=(o?"https://":"http://")+"ac.open.phpwind.com/b.gif",z={},i=location.href,$=f.referrer,W=location.pathname,x=o&&(0<=i.indexOf("login.taobao.com")||0<=i.indexOf("login.tmall.com")),K=!!f.attachEvent,U=K?"attachEvent":
"addEventListener",y=!1,L=!0,s="::-plain-::",aa=Math.random(),ba=v(i),r,p,E,k={},q={},u,l,m,H,n;n={send:function(a,b){var c=new Image,d="_img_"+Math.random(),f=-1==a.indexOf("?")?"?":"&",g=h(b);e[d]=c;c.onload=c.onerror=function(){e[d]=null};c.src=f=g?a+f+g:a;c=null;return f},emit:function(a,b){var c=B(b);c["_gm:id"]=a;return n.record("ued.1.1.2?type=9",{},c,"%")},record:function(a,b,c,d){d=d||null;if(!("%"!=d&&v(i)!=d)&&!(1<N(b)))return a=Y+a,c=B(c),d=-1==a.indexOf("?")?"?":"&",1==N(b)&&(a+=d+h(b)),
c._r_=Math.random(),n.send(a,c)}};e.goldlog=n;e.goldminer={record:n.emit};e.goldlog_queue=[];X();Q();S();T();(function(){var a,b=G("cna"),c=G("tracknick"),d=k.pageId,h=k.prototypeId;if(!w||V())a={acookie_load_id:""+(Math.floor(9999999999*Math.random())+1)+(Math.floor(9999999999*Math.random())+1),title:f.title,pre:$,cache:Math.floor(9999999*aa+1),scr:screen.width+"x"+screen.height,isbeta:3,ul_chk:ba},a[s+Math.random()]=P(),b&&(a[s+Math.random()]="cna="+b),c&&(a.nick=c),r&&(a.upi_bi=r),d&&(a.wm_pageid=
d),h&&(a.wm_prototypeid=h),u&&(a.wm_sid=u),l&&"i"!=H&&(a["spm-cnt"]=l),C(z,a),e.g_aplus_pv_req=O(Z,z);if(w){R();var g;a=q.on;b=("1"==a?"http://ac":"http://www")+".atpanel.com/b.gif";("1"==a||"2"==a)&&((g=q.chksum)&&g===v(i).toString())&&O(b,z)}x?I():J(e,"beforeunload",function(){I()})})()}})();
